### ISSUE TITLE
Contact request

### ISSUE THREAD

**Issue by iamdiogo** [iamdiogo/DarkCloud#11]
Hey @MyNameIsJulian . Could you add an email address to your GitHub account so I may reach you?

Thanks

**Comment by MyNameIsJulian** [comment]
Hi, could you add me on Tox?

Find my ID here: https://privatebin.net/?2b6ef19d25525665#7sB9EtWshWgd4jweWRikTXs7RaBJNp1Cq7xm4n2MnpkA
