### ISSUE TITLE
Comments disabled box broken

### ISSUE THREAD

**Issue by Franckevicius** [iamdiogo/DarkCloud#13]
Example (https://soundcloud.com/sibewest/luna-lutiki-sibewest-remix-demo-lost-project)

**Comment by iamdiogo** [comment]
Thank you. I'll fix this later this week

**Comment by MyNameIsJulian** [comment]
This issue has been resolved (https://github.com/iamdiogo/DarkCloud/commit/a9e8b6069b378775c49f2ed904063ee6990f87e3) and the changes will take effect in the next update.

Thanks for reporting!
