### ISSUE TITLE
Dark names over dark background in featured profiles section

### ISSUE THREAD

**Issue by Franckevicius** [iamdiogo/DarkCloud#15]
Not really readable. Perhaps change it to grey/white, the same as follower count and track count?
`featuredProfiles__list`

**Comment by MyNameIsJulian** [comment]
Fixed in https://github.com/iamdiogo/DarkCloud/commit/cbea5536935f062c13df72f866f24b138c1d8ba7  & https://github.com/iamdiogo/DarkCloud/commit/96f24da1c3a81ecfb0cac517a14977288c21b1ae :smile:
