### ISSUE TITLE
Icons are blacked out when hovering over tracks in playlist previews at /discover

### ISSUE THREAD

**Issue by Franckevicius** [iamdiogo/DarkCloud#16]
Like, repost & share mini icons are invisible. This is valid for any playlist preview in the /discover section. If saved/reposted/shared, orange icons are visible. 
[Example](https://i.imgur.com/ApgYqtV.png)

**Comment by iamdiogo** [comment]
Fixed in e9f7edf33b89e82d4402566f3bfc65fb2aa1ed16

Thanks! :slightly_smiling_face:
