### ISSUE TITLE
Unavailable link to chrome webstore in Readme

### ISSUE THREAD

**Issue by nikelborm** [iamdiogo/DarkCloud#19]
https://chrome.google.com/webstore/detail/darkcloud/mjicdmidmifkppilbbcanmnljpffmfmh

**Comment by iamdiogo** [comment]
Thank you @nikelborm 

It seems it has been taken down, due to new policies in the web store.

I've filled new information and is now awaiting review

**Comment by iamdiogo** [comment]
It has been reviewed and accepted by the chrome webstore team. Thank you for noticing it.
