### ISSUE TITLE
Subscriptions page is not darkened

### ISSUE THREAD

**Issue by juanoliveira82** [iamdiogo/DarkCloud#23]
### On the right is the normal soundcloud.

![subs](https://user-images.githubusercontent.com/19778952/142772839-5ea46816-b00c-4b2a-8ab3-e7966d699c0b.PNG)

Also those orange bars used to separate elements on the website are ugly, they could be a lighter orange, or gray.

**Comment by iamdiogo** [comment]
Doesn't seem to be the case anymore 👌
