### ISSUE TITLE
Deploy addon as Firefox extension

### ISSUE THREAD

**Issue by Zocker1999NET** [iamdiogo/DarkCloud#3]
Do you might want to upload this extension to the Firefox Addon Repository?
I can confirm this extension works with Firefox Version 66.0.1.

Firefox does only complain about a part of the `manifest.json`,
but it does not break the functionality and performance:
https://github.com/iamdiogo/DarkCloud/blob/eecaa000977dbbfcf971b93e65e6c22b0da69c42/manifest.json#L9

The warning is:
```
Reading manifest: Error processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.
```

EDIT: Also you would need to add an add-on id for the gecko engine, which Chrome should simply ignore:
```json
  "applications": {
    "gecko": {
      "id": "{444a63a7-2655-4de6-828e-c4d9b194d54f}"
    }
  },
```

**Comment by iamdiogo** [comment]
Thank you for all your great suggestions. I'll check this out later today and see what problems I might encounter while adding Firefox support.

**Comment by iamdiogo** [comment]
Hey @Zocker1999NET , I've just added Firefox support by completely removing the persistent key.
It's published here: https://addons.mozilla.org/en-US/firefox/addon/darkcloud-original/
Thank you for pointing it out.

**Comment by Zocker1999NET** [comment]
Thank you for uploading your addon for Firefox :)
