### ISSUE TITLE
the Soundcloud comments now look unreadable due to an update

### ISSUE THREAD

**Issue by MimiDotTee** [iamdiogo/DarkCloud#33]
Soundcloud updated how the comments look and it now looks unreadable with this addon since the black text doesn't look good with the blackish/grey background.

![image](https://github.com/iamdiogo/DarkCloud/assets/37915966/79f59cf4-b9ee-4a6f-8a2b-ab0196511237)

**Comment by kevinization** [comment]
Same, waiting for an update.

**Comment by iamdiogo** [comment]
Pushed an update 👍 

As soon as it passes review it'll be fixed

**Comment by vittoopugliese** [comment]
nice
